name: electron_avenue
description: Improve your design and learn to use our advanced component backdrop menu for Flutter.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  #  cupertino_icons: ^1.0.3
  shrine_images: ^2.0.1
  shared_preferences: ^2.0.15
  firebase_core: ^2.4.0
  firebase_database: ^10.0.7
  firebase_auth: ^4.2.0
  text_form_field_wrapper: ^1.0.0
  url_launcher: ^6.1.7
  favorite_button: ^0.0.4
  cached_network_image: ^3.2.3
  lottie: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500

  uses-material-design: true
  assets:
    - assets/images/
    - assets/diamond.png
    - assets/slanted_menu.png
