name: shrine
description: Improve your design and learn to use our advanced component backdrop menu for Flutter.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  #  cupertino_icons: ^1.0.3
  shrine_images: ^2.0.1
  shared_preferences: ^2.0.15
  firebase_core: ^1.24.0
  firebase_database: ^9.1.7
  firebase_auth: ^3.11.2
  checkout_screen_ui: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500

  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/slanted_menu.png
